version: "3.9"

services:
     web:
          build: .
          ports:
               - "5000:5000"
          environment:
               FLASK_ENV: development

          volumes:
               - .:/app

     db:
          image: postgres:13
          volumes:
               - postgres_data:/var/lib/postgresql/data

          environment:
               POSTGRES_DB: WWW
               POSTGRES_USER: postgres
               POSTGRES_PASSWORD: 13666

volumes:
     postgres_data:
